# redis = redis server
# web   = Dash Web-App
# worker = redis worker runs Nextflow
# rnaseqnet = a private network

services:
  redis:
    image: redis:7-alpine
    container_name: rnaseq_redis
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [rnaseqnet]

  web:
    build: .
    container_name: rnaseq_web
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    command: ["python", "-u", "index.py"]
    environment:
      HOST: "0.0.0.0"
      PORT: "${WEB_PORT:-8051}"
      DEBUG: "${DEBUG:-0}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      BASE_DIR: "/home/azureuser/APPLICATION/temp_rnaseq_run"
    ports:
      - "${WEB_PORT:-8051}:${WEB_PORT:-8051}"
    volumes:
      - .:/workspace
      - /home/azureuser/APPLICATION:/home/azureuser/APPLICATION
      - /home/azureuser/.bfabricpy.yml:/home/azureuser/.bfabricpy.yml:ro
    working_dir: /workspace
    networks: [rnaseqnet]

  # The worker runs as root and mounts the Docker socket.
  # This combination grants full control over the host’s Docker daemon (root-equivalent access).
  # It is required by Nextflow to handle file permissions and launch Dockerized processes.
  worker:
    build: .
    container_name: rnaseq_worker
    user: "0" # run as root (needed for Nextflow & file permissions)
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    command: ["python", "-u", "scripts/worker.py", "--queues=light,heavy"]
    environment:
      NXF_DOCKER_OPTS: "--user 0:0" # ensures all Nextflow-launched Docker containers run as root (avoid permission issues)
      NEXTFLOW_BIN: "/home/azureuser/.local/bin/nextflow" # path to the Nextflow executable inside the container
      NXF_HOME: "/workspace/.nextflow"  # directory where Nextflow stores its cache, logs, and temporary work files
      UID: "0"  # user id
      GID: "0"  # group id

      HOST: "0.0.0.0"
      PORT: "${WEB_PORT:-8051}"
      DEBUG: "${DEBUG:-0}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      BASE_DIR: "/home/azureuser/APPLICATION/temp_rnaseq_run"
      OUTPUT_DIR: "/home/azureuser/STORAGE"
    volumes:
      - .:/workspace
      - /home/azureuser/APPLICATION:/home/azureuser/APPLICATION
      - /home/azureuser/STORAGE:/home/azureuser/STORAGE
      - /var/run/docker.sock:/var/run/docker.sock # gives container access to host Docker daemon (Nextflow can spawn docker containers)
      - /home/azureuser/.bfabricpy.yml:/root/.bfabricpy.yml:ro
      - /home/azureuser/.ssh:/home/azureuser/.ssh:ro
      - /home/azureuser/.ssh:/root/.ssh:ro 
    working_dir: /workspace
    networks: [rnaseqnet]

networks:
  rnaseqnet:
    driver: bridge
